### ISSUE TITLE
importlib_resources does not have the name open_text 

### ISSUE THREAD

**Issue by cactuskid** [Ad115/EnsemblRest#4]
after installing on python 3.10 I get the following error

> ImportError                               Traceback (most recent call last)
Cell In[2], line 1
----> 1 import ensembl_rest

File /work/FAC/FBM/DBC/cdessim2/default/dmoi/miniconda3/envs/ML2/lib/python3.10/site-packages/ensembl_rest/__init__.py:1
----> 1 from .ensemblclient import EnsemblClient, _api_table
      2 from .core import HTTPError, InvalidResponseError, _endpoint_docstring
      3 from .assemblymapper import AssemblyMapper

File /work/FAC/FBM/DBC/cdessim2/default/dmoi/miniconda3/envs/ML2/lib/python3.10/site-packages/ensembl_rest/ensemblclient.py:11
      1 """
      2 
      3 This file is part of pyEnsemblRest.
   (...)
      7 
      8 """
     10 import json
---> 11 from importlib_resources import open_text, path
     12 from .core import build_client_class
     14 # Import API information

ImportError: cannot import name 'open_text' from 'importlib_resources' (/work/FAC/FBM/DBC/cdessim2/default/dmoi/miniconda3/envs/ML2/lib/python3.10/site-packages/importlib_resources/__init__.py)

**Comment by k-tetley-campbell** [comment]
Hi, I had the same issue today but I mananged to solve the issue by editing line 11 above from importlib_resources to  importlib.resources

**Comment by cactuskid** [comment]
thanks for the comment. I submitted a pull request.

**Comment by Ad115** [comment]
Thanks @cactuskid! Just merged the PR. Will update the pip package shortly
